### PR TITLE
Multiple accounts

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Enable the usage of multiple O365 accounts

### CODE REVIEW

**Comment by aaronpowell** [comment]
Giving this branch a whirl and I've hit an error with it starting up, here's the error:

```
Logger: homeassistant.setup
Source: helpers/network.py:172
First occurred: 21:58:30 (1 occurrences)
Last logged: 21:58:30

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 65, in async_setup
    _setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 90, in _setup_account
    _request_authorization(hass, account_conf, account, account_name, conf_type)
  File "/config/custom_components/o365/__init__.py", line 189, in _request_authorization
    callback_url = _get_callback_url(hass, alt_config)
  File "/config/custom_components/o365/__init__.py", line 211, in _get_callback_url
    return f"{get_url(hass, prefer_external=True)}{AUTH_CALLBACK_PATH}"
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 133, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 172, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

Config:

```yaml
accounts:
    - account_name: Aaron
      client_id: !secret o365_aaron_client_id
      client_secret: !secret o365_aaron_client_secret
      enable_update: True
      email_sensor:
        - name: Aaron's inbox
          folder: Inbox
          max_items: 10
          is_unread: True
          download_attachments: False
      status_sensors:
        - name: "Aaron's Teams status"
```

I know the client_id/client_secret are valid (I was using them before the upgrade to 3.0.0a8).

Thoughts on what that might be, or how to debug further?

**Comment by RogerSelwyn** [comment]
> Giving this branch a whirl and I've hit an error with it starting up, here's the error:
> 
> ```
> Logger: homeassistant.setup
> Source: helpers/network.py:172
> First occurred: 21:58:30 (1 occurrences)
> Last logged: 21:58:30
> 
> Error during setup of component o365
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
>     result = await task
>   File "/config/custom_components/o365/__init__.py", line 65, in async_setup
>     _setup_account(hass, account, conf_type)
>   File "/config/custom_components/o365/__init__.py", line 90, in _setup_account
>     _request_authorization(hass, account_conf, account, account_name, conf_type)
>   File "/config/custom_components/o365/__init__.py", line 189, in _request_authorization
>     callback_url = _get_callback_url(hass, alt_config)
>   File "/config/custom_components/o365/__init__.py", line 211, in _get_callback_url
>     return f"{get_url(hass, prefer_external=True)}{AUTH_CALLBACK_PATH}"
>   File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 133, in get_url
>     request_host = _get_request_host()
>   File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 172, in _get_request_host
>     raise NoURLAvailableError
> homeassistant.helpers.network.NoURLAvailableError
> ```
> 
> Config:
> 
> ```yaml
> accounts:
>     - account_name: Aaron
>       client_id: !secret o365_aaron_client_id
>       client_secret: !secret o365_aaron_client_secret
>       enable_update: True
>       email_sensor:
>         - name: Aaron's inbox
>           folder: Inbox
>           max_items: 10
>           is_unread: True
>           download_attachments: False
>       status_sensors:
>         - name: "Aaron's Teams status"
> ```
> 
> I know the client_id/client_secret are valid (I was using them before the upgrade to 3.0.0a8).
> 
> Thoughts on what that might be, or how to debug further?

Do you use alt_auth_flow as False (or not present) previously? This is it failing to get an external url from HA as configured in the settings of your HA instance.

**Comment by RogerSelwyn** [comment]
> 
> Do you use alt_auth_flow as False (or not present) previously? This is it failing to get an external url from HA as configured in the settings of your HA instance.

I can't even force my dev instance to generate that error, so there is something weird with your HTTP setup on your HA instance.

**Comment by RogerSelwyn** [comment]
Looks like you are using an older version of HA than I am which could be why I can't get the error (I can see they have made changes recently), but could be worth just using alternate path of authentication if you can't figure out what is wrong with your http config.

**Comment by aaronpowell** [comment]
> Do you use alt_auth_flow as False (or not present) previously? This is it failing to get an external url from HA as configured in the settings of your HA instance.

That's it - I forgot that I'd used that previously (must have removed it from the config before my last git push).

Added in and it works now, thanks - I'll see about testing multiple accounts now

**Pull request merged**
