### PR TITLE
Add support for shared mailboxes

### PR DESCRIPTION
**Pull request by jgrieger1**
Adds support for creating an account that can be used to access a shared mailbox.

A new account configuration parameter called 'shared_mailbox' is used to specify the shared mailbox that the account will access.  The user authenticating must have permissions to access the shared mailbox.  The app registration will need the following additional permissions:

enable_update = false
- Calendars.Read.Shared
- Mail.Read.Shared
- Tasks.Read.Shared

enable_update = true
- Calendars.ReadWrite.Shared
- Mail.ReadWrite.Shared
- Tasks.ReadWrite.Shared

If shared_mailbox is specified, Calendar, Email, and ToDo features will use the mailbox specified by shared_mailbox.

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
As far as I know you can already access a shared mailbox, or at least I do with my current setup (unless of course what I have isn't a shared mailbox, pretty sure it is though).

**Comment by RogerSelwyn** [comment]
Though when I look at this code it looks like you are setting the base as that shared mailbox, rather than accessing it as an extra mailbox to the primary one.

**Comment by RogerSelwyn** [comment]
What value is set to 'shared_mailbox'? Is it email address or a guid?

**Comment by jgrieger1** [comment]
> As far as I know you can already access a shared mailbox, or at least I do with my current setup (unless of course what I have isn't a shared mailbox, pretty sure it is though).

The only way I see this possible is if the shared mailbox is associated with a user account with a valid license and you authenticate with this user.  In my case, I have several shared mailboxes but the user accounts associated with these do not have a license and cannot authenticate.  This helps reduce the number of required licenses keeping costs down.

**Comment by jgrieger1** [comment]
> What value is set to 'shared_mailbox'? Is it email address or a guid?

The shared mailbox primary email address.  When creating a shared mailbox, Exchange 365 creates a user account using the shared mailbox primary email address.

**Comment by RogerSelwyn** [comment]
I use mailbox

> > As far as I know you can already access a shared mailbox, or at least I do with my current setup (unless of course what I have isn't a shared mailbox, pretty sure it is though).
> 
> The only way I see this possible is if the shared mailbox is associated with a user account with a valid license and you authenticate with this user. In my case, I have several shared mailboxes but the user accounts associated with these do not have a license and cannot authenticate. This helps reduce the number of required licenses keeping costs down.

It seems to allow me to create unlicensed users (I guess they may previously have been public folders), which I then set a password on. Then I can add them as extra users in my outlook config.

**Comment by RogerSelwyn** [comment]
Just checked I create 'shared mailbox', then I think I added a password via the user panel, then I can add to outlook...

**Comment by RogerSelwyn** [comment]
Ok, I'll look at it in the next few days. It needs some more work on permissions so that they are requested and checked correctly and some documentation adding.

**Comment by jgrieger1** [comment]
The following has a Note regarding the usage of the shared mailbox user account.
https://learn.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide

Thanks for looking at this, and thank you for continuing the maintenance for this integration!

**Comment by RogerSelwyn** [comment]
Did you validate that this works for Tasks? When I enable it, it fails with the below

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/fred@redacted.co.uk/todo/lists | Error Message: Invalid request`

**Comment by RogerSelwyn** [comment]
Also this error in Graph API

```
{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid request",
        "innerError": {
            "code": "ErrorIncorrectRoutingHint",
            "date": "2023-05-04T10:06:52",
            "request-id": "6a30c992-f9ba-47ed-8317-d41901165bd2",
            "client-request-id": "94c535c3-62c7-5ae4-1dae-d5c3093a0f6b"
        }
    }
}
```

**Comment by RogerSelwyn** [comment]
It seems even though there are permissions for it, it isn't supported.

https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1620

**Comment by RogerSelwyn** [comment]
Please can you test the changes I have made.

**Pull request merged**
