### PR TITLE
Change icon of Team Status Sensor to real Teams Icon

### PR DESCRIPTION
**Pull request by rdeveen**
The icon of the Teams Status Sensor is just the default eye icon. The Teams icon is available in the icons library. This PR will use the Teams Icon in the Teams Status Sensor.

Before
Screenshot 2022-11-12 204337
After
Screenshot 2022-11-12 204702

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
I've not tested it, but you can probably use the icon property for this, rather than extra_attributes. Certainly works for media_player not sure if it works for sensor.

```
    @property
    def icon(self):
        """Entity icon."""
        return SKYQ_ICONS[self._entity_attr.skyq_media_typer]
```

**Comment by rdeveen** [comment]
You are right, changed it.

**Comment by RogerSelwyn** [comment]
I'll have a look at this some more tomorrow, and probably add icons for the chat sensor (teams), and the inbox sensors (outlook). I'm just implementing a tasks/todo sensor, so will look if there is anything appropriate for that.

Great idea. Thanks

**Comment by rdeveen** [comment]
It's my pleasure.

Here are some ideas for other icons.

For Chat: `mdi:chat`
For Inbox: `mdi-email`
For Tasks: `mdi:bookmark-check` or `mdi:clipboard-check`

**Pull request merged**
